"""initial migrate

Revision ID: a1040320cbff
Revises: 
Create Date: 2020-07-19 10:21:32.841873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1040320cbff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('on_menu', sa.Boolean(), nullable=True))
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('store', sa.Column('active', sa.Boolean(), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('store', 'active')
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('category', 'on_menu')
    # ### end Alembic commands ###
